//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambrosium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        public int id { get; set; }
        public int rating { get; set; }
        public string comentario { get; set; }
        public System.DateTime data { get; set; }
        public int produto { get; set; }
        public int utilizador { get; set; }
    
        public virtual Produto Produto1 { get; set; }
        public virtual Utilizador Utilizador1 { get; set; }
    }
}
