//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambrosium.Models
{
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Globalization;
    using System.IO;
    using System.Net;

    public partial class Estabelecimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estabelecimento()
        {
            this.Galeria = new HashSet<Galeria>();
            this.Horario = new HashSet<Horario>();
            this.Produto = new HashSet<Produto>();
            this.Sugestao_Estabelecimento = new HashSet<Sugestao_Estabelecimento>();
        }

        public void load(string place_id)
        {
            WebRequest request = WebRequest.Create("https://maps.googleapis.com/maps/api/place/details/json?placeid=" + place_id + "&key=AIzaSyA_cNufnfv4_Mad0We1ZQZxWyHG6zE_x44");
            WebResponse response = request.GetResponse();

            Stream dataStream = response.GetResponseStream();
            StreamReader reader = new StreamReader(dataStream);
            string content = reader.ReadToEnd();

            JObject jEstabelecimento = JObject.Parse(content);

            this.nome = (string)jEstabelecimento["result"]["name"];
            this.localizacao = (string)jEstabelecimento["result"]["formatted_address"];
            this.telefone = (string)jEstabelecimento["result"]["formatted_phone_number"];
            this.rating = float.Parse((string)jEstabelecimento["result"]["rating"], CultureInfo.InvariantCulture.NumberFormat);

            var jHorarios = jEstabelecimento["result"]["opening_hours"];
            if (jHorarios != null)
                this.SetHorarios(jHorarios["periods"]);
        }

        private void SetHorarios(JToken jHorarios)
        {
            Horario[] horarios = new Horario[7];
            for (int i = 0; i < horarios.Length; i++)
            {
                horarios[i] = new Horario();
                horarios[i].dia = i;
            }

            foreach (var item in jHorarios)
            {
                int close_day = int.Parse((string)item["close"]["day"]);
                string close_time = (string)item["close"]["time"];
                int close_hour = int.Parse(close_time.Substring(0, 2));
                int close_minute = int.Parse(close_time.Substring(2, 2));

                int open_day = int.Parse((string)item["open"]["day"]);
                string open_time = (string)item["open"]["time"];
                int open_hour = int.Parse(open_time.Substring(0, 2));
                int open_minute = int.Parse(open_time.Substring(2, 2));

                if (horarios[close_day].fecho == null)
                    horarios[close_day].fecho = new TimeSpan(close_hour, close_minute, 0);
                else
                    horarios[close_day].fecho2 = new TimeSpan(close_hour, close_minute, 0);

                if (horarios[open_day].abertura == null)
                    horarios[open_day].abertura = new TimeSpan(open_hour, open_minute, 0);
                else
                    horarios[open_day].abertura2 = new TimeSpan(open_hour, open_minute, 0);
            }

            foreach (Horario h in horarios)
                this.Horario.Add(h);
        }

        public int id { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string telefone { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.##}")]
        public Nullable<double> rating { get; set; }
        public string localizacao { get; set; }
        public byte ativo { get; set; }
        public byte sugestoes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Galeria> Galeria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario> Horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produto> Produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sugestao_Estabelecimento> Sugestao_Estabelecimento { get; set; }

        // Devolve a distancia de origins ao estabelecimento em questão em metros.
        public int GetDistance(string origins)
        {
            return DistanceMatrix.GetDistanceValue(origins, this.localizacao);
        }

        // Devolve a distância de origins ao estabelecimento de maneira legível
        public string GetDistancePrintable(string origins)
        {
            return DistanceMatrix.GetDistanceText(origins, this.localizacao);
        }

        public List<ISugestao> GetSugestoes()
        {
            List<ISugestao> ret = new List<ISugestao>();

            foreach (Sugestao_Estabelecimento se in Sugestao_Estabelecimento)
                ret.Add((ISugestao)se);

            foreach (Produto p in Produto)
                foreach (Sugestao_Produto sp in p.Sugestao_Produto)
                    ret.Add((ISugestao)sp);

            return ret;
        }

        public List<Produto> getProdutos(string product)
        {
            List<Produto> ret = new List<Models.Produto>();

            foreach (Produto p in Produto)
                if (p.nome.Contains(product)) ret.Add(p);

            return ret;
        }
    }
}
