//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambrosium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int id { get; set; }
        public int dia { get; set; }
        public int estabelecimento { get; set; }
        public System.TimeSpan abertura { get; set; }
        public System.TimeSpan fecho { get; set; }
        public Nullable<System.TimeSpan> abertura2 { get; set; }
        public Nullable<System.TimeSpan> fecho2 { get; set; }
    
        public virtual Estabelecimento Estabelecimento1 { get; set; }
    }
}
