//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambrosium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sugestão
    {
        public int id { get; set; }
        public string tipo { get; set; }
    
        public virtual Sugestao_Estabelecimento Sugestao_Estabelecimento { get; set; }
        public virtual Sugestao_Produto Sugestao_Produto { get; set; }
    }
}
