//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambrosium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sugestao_Ingrediente
    {
        public int sugestao { get; set; }
        public string ingrediente { get; set; }
    
        public virtual Ingrediente Ingrediente1 { get; set; }
    }
}
