//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambrosium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sugestao_Produto
    {
        public int id { get; set; }
        public string nome { get; set; }
        public System.DateTime data { get; set; }
        public string regime { get; set; }
        public int utilizador { get; set; }
        public int Sugestão_id { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Regime Regime1 { get; set; }
        public virtual Sugestão Sugestão { get; set; }
        public virtual Utilizador Utilizador1 { get; set; }
    }
}
